// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdecG9blRaY3MNQXMfTMzlYTveS6skhw',
    appId: '1:675148664116:web:7201fee3e1ef413956a961',
    messagingSenderId: '675148664116',
    projectId: 'floodlg',
    authDomain: 'floodlg.firebaseapp.com',
    databaseURL: 'https://floodlg-default-rtdb.firebaseio.com',
    storageBucket: 'floodlg.firebasestorage.app',
    measurementId: 'G-0CF1V6M95B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbw5lGMIRvKKF2sVDKYJX25IbTc32PfM0',
    appId: '1:675148664116:android:1fff106c6430443556a961',
    messagingSenderId: '675148664116',
    projectId: 'floodlg',
    databaseURL: 'https://floodlg-default-rtdb.firebaseio.com',
    storageBucket: 'floodlg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxH1oF7k_qIDosTOhpkLUcjpU5Xq2p8M',
    appId: '1:675148664116:ios:f92c1f13f27608de56a961',
    messagingSenderId: '675148664116',
    projectId: 'floodlg',
    databaseURL: 'https://floodlg-default-rtdb.firebaseio.com',
    storageBucket: 'floodlg.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoxH1oF7k_qIDosTOhpkLUcjpU5Xq2p8M',
    appId: '1:675148664116:ios:f92c1f13f27608de56a961',
    messagingSenderId: '675148664116',
    projectId: 'floodlg',
    databaseURL: 'https://floodlg-default-rtdb.firebaseio.com',
    storageBucket: 'floodlg.firebasestorage.app',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcdecG9blRaY3MNQXMfTMzlYTveS6skhw',
    appId: '1:675148664116:web:f705c820e6eac09556a961',
    messagingSenderId: '675148664116',
    projectId: 'floodlg',
    authDomain: 'floodlg.firebaseapp.com',
    databaseURL: 'https://floodlg-default-rtdb.firebaseio.com',
    storageBucket: 'floodlg.firebasestorage.app',
    measurementId: 'G-C4F90JC5BK',
  );

}